version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Bind mount the Docker socket
    ports:
      - "3000:3000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge